version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    env_file:
      - .env
    volumes:
      - .:/app
      
    # Override the CMD to use the dynamic port
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port $${PORT:-8000} --reload"